<?php

namespace Database\Factories;

use App\Models\Categoria;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Producto>
 */
class ProductoFactory extends Factory
{

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $productos = [
            'Champú revitalizante',
            'Pasta dental blanqueadora',
            'Jabón líquido antibacterial',
            'Desodorante en barra fresco',
            'Novela de misterio',
            'Libro de cocina saludable',
            'Zapatillas para entrenamiento',
            'Zapatillas para senderismo',
            'Zapatillas de fútbol sala',
            'Camiseta de algodón suave',
            'Jeans de corte clásico',
            'Blusa elegante de seda',
            'Chaqueta deportiva transpirable',
            'Reloj de pulsera resistente al agua',
            'Bolso de viaje resistente',
            'Lámpara de lectura LED',
            'Gel de ducha revitalizante',
            'Libro de poesía contemporánea',
            'Shorts deportivos cómodos',
            'Calcetines de algodón transpirables',
            'Blazer de moda para ocasiones especiales',
            'Reloj inteligente con monitor de actividad',
            'Gorra de béisbol ajustable',
            'Cinturón de cuero genuino',
            'Vestido casual de verano',
            'Cepillo de dientes eléctrico recargable',
            'Pantalones de yoga elásticos',
            'Acondicionador nutritivo para el cabello',
            'Bolso de mano elegante',
            'Libro de historia del arte',
            'Sneakers urbanos de moda',
            'Chaqueta de invierno acolchada',
            'Blusa de encaje elegante',
            'Calcetines de deporte acolchados',
            'Jersey de lana suave',
            'Plancha de pelo de cerámica',
            'Perfume floral y fresco',
            'Pijama de algodón suave',
            'Champú sin sulfatos',
            'Mochila resistente al agua',
            'Botines de cuero genuino',
            'Cárdigan de punto ligero',
            'Pulsera de plata con piedras preciosas',
            'Billetera de cuero clásica',
            'Gafas de sol de diseño',
            'Blusa estampada de estilo boho',
            'Pantalones chinos de corte moderno',
            'Reloj de pulsera de titanio',
            'Bolso de mano con estampado floral',
            'Calcetines divertidos con diseños originales',
            'Camisa de lino fresca',
            'Zapatillas de casa cómodas',
            'Lámpara de escritorio LED regulable',
            'Sudadera con capucha y bolsillos',
            'Libro de autoayuda y motivación',
            'Shorts vaqueros desgastados',
            'Bolso de hombro con correa ajustable',
            'Gorra de visera curva',
            'Bufanda de lana suave',
            'Reloj analógico de estilo vintage',
            'Zapatillas de skate resistentes',
            'Cartera de mano elegante',
            'Cinturón reversible para hombres',
            'Camiseta de tirantes deportiva',
            'Pantalones de vestir clásicos',
            'Abrigo largo de lana',
            'Vestido de cóctel elegante',
            'Zapatillas de ballet cómodas',
            'Gorra de punto con pompón',
            'Bufanda infinita de colores',
            'Botines de ante con tacón',
            'Mochila de cuero vintage',
            'Sneakers altos de estilo retro',
            'Chaqueta vaquera con forro de borreguito',
            'Pulsera de cuero trenzado',
            'Bolso bandolera de tela resistente',
            'Collar de plata con colgante',
            'Cárdigan de lana merino',
            'Gafas de sol polarizadas',
            'Calcetines de lana para el invierno',
            'Reloj automático de lujo',
            'Blusa de manga larga a rayas',
            'Pantalones cargo resistentes',
            'Champú sin parabenos',
            'Zapatillas de montaña impermeables',
            'Camiseta de algodón orgánico',
            'Vestido maxi con estampado floral',
            'Bolso tote de piel sintética',
            'Gorra de béisbol con diseño vintage',
            'Cinturón de lona ajustable',
            'Pulsera de perlas naturales',
            'Chaqueta de cuero auténtico',
            'Libro de suspense psicológico',
            'Shorts de baño de secado rápido',
            'Pantalones de yoga de alta calidad',
            'Blusa de encaje delicado',
            'Sneakers urbanos de colores vivos',
            'Reloj digital deportivo',
            'Bolso cruzado de nailon resistente',
            'Calcetines deportivos de compresión',
            'Vestido de noche elegante',
            'Gorra trucker con diseño gráfico',
            'Bufanda de cachemira suave',
            'Perfume con fragancia oriental',
            'Sudadera con cuello alto',
            'Cartera de cuero con monedero',
            'Zapatillas de running para hombres',
            'Chaqueta acolchada para mujer',
            'Pantalones cortos de ciclismo',
            'Gafas de sol de aviador clásicas',
            'Camiseta de manga larga de algodón',
            'Reloj suizo de alta gama',
            'Blusa estampada de flores',
            'Botas de montaña resistentes',
            'Bufanda de lana de alpaca',
            'Calcetines térmicos de invierno',
            'Abrigo de paño clásico',
            'Vestido de novia de ensueño',
        ];
        return [
            'categoria_id' => Categoria::inRandomOrder()->first()->id,
            'nombre' => fake()->randomElement($productos),
            'descripcion' => fake()->text(),
            'precio' => fake()->numberBetween(10000,500000),
            'cantidad' => fake()->randomNumber(2)
        ];
    }
}
